import type { GoalTemplate } from '@/types'

export const GOAL_TEMPLATES: GoalTemplate[] = [
  {
    id: 'tpl_education',
    name: "Child's Higher Education",
    category: 'EDUCATION',
    description: 'Fund higher education for your child in India or abroad',
    icon: 'GraduationCap',
    defaultTargetYears: 15,
    defaultAmount: 2500000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50'],
  },
  {
    id: 'tpl_home',
    name: 'Home Downpayment',
    category: 'HOME_PURCHASE',
    description: 'Save for the down payment on your dream home',
    icon: 'Home',
    defaultTargetYears: 5,
    defaultAmount: 1500000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50'],
  },
  {
    id: 'tpl_emergency',
    name: 'Emergency Fund',
    category: 'EMERGENCY_FUND',
    description: '6 months of expenses as a financial safety net',
    icon: 'Shield',
    defaultTargetYears: 1,
    suggestedAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_travel',
    name: 'Annual Vacation',
    category: 'TRAVEL',
    description: 'Plan and fund your annual travel or dream vacation',
    icon: 'Plane',
    defaultTargetYears: 1,
    defaultAmount: 200000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_vehicle',
    name: 'Vehicle Purchase',
    category: 'VEHICLE',
    description: 'Save for a car, bike, or other vehicle',
    icon: 'Car',
    defaultTargetYears: 3,
    defaultAmount: 1500000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50'],
  },
  {
    id: 'tpl_real_estate',
    name: 'Real Estate Purchase',
    category: 'REAL_ESTATE',
    description: 'Buy a plot, second home, or investment property',
    icon: 'Building',
    defaultTargetYears: 10,
    defaultAmount: 5000000,
    suggestedAgeGroups: ['30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_retirement',
    name: 'Retirement Corpus',
    category: 'RETIREMENT',
    description: 'Build a corpus to sustain your lifestyle post-retirement',
    icon: 'Sunset',
    defaultTargetYears: 25,
    defaultAmount: 10000000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_business',
    name: 'Business Capital',
    category: 'BUSINESS',
    description: 'Fund your entrepreneurial venture or startup',
    icon: 'Briefcase',
    defaultTargetYears: 5,
    defaultAmount: 2000000,
    suggestedAgeGroups: ['20_30', '30_40'],
  },
  {
    id: 'tpl_legacy',
    name: 'Legacy / Inheritance',
    category: 'LEGACY_INHERITANCE',
    description: 'Build wealth to pass on to your family or future generations',
    icon: 'Crown',
    defaultTargetYears: 20,
    defaultAmount: 5000000,
    suggestedAgeGroups: ['40_50', '50_PLUS'],
  },
  {
    id: 'tpl_loan',
    name: 'Loan Foreclosure',
    category: 'LOAN_FORECLOSURE',
    description: 'Save to foreclose an existing home, car, or personal loan early',
    icon: 'Landmark',
    defaultTargetYears: 3,
    defaultAmount: 1000000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50'],
  },
  {
    id: 'tpl_critical_illness',
    name: 'Critical Illness Cover',
    category: 'CRITICAL_ILLNESS',
    description: 'Build a fund to cover treatment for critical illnesses',
    icon: 'HeartPulse',
    defaultTargetYears: 1,
    defaultAmount: 500000,
    suggestedAgeGroups: ['30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_life_protection',
    name: 'Life Protection',
    category: 'LIFE_PROTECTION',
    description: 'Ensure your family is financially protected in your absence',
    icon: 'ShieldCheck',
    defaultTargetYears: 1,
    defaultAmount: 10000000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50'],
  },
  {
    id: 'tpl_family_health',
    name: 'Family Health Cover',
    category: 'FAMILY_HEALTH',
    description: 'Build a health corpus or fund a comprehensive family health plan',
    icon: 'Activity',
    defaultTargetYears: 1,
    defaultAmount: 300000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_childs_marriage',
    name: "Child's Marriage",
    category: 'CHILDS_MARRIAGE',
    description: "Save for your child's wedding expenses",
    icon: 'Heart',
    defaultTargetYears: 15,
    defaultAmount: 2000000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50'],
  },
  {
    id: 'tpl_own_marriage',
    name: 'Own Marriage',
    category: 'OWN_MARRIAGE',
    description: 'Plan and save for your own wedding',
    icon: 'Heart',
    defaultTargetYears: 3,
    defaultAmount: 1500000,
    suggestedAgeGroups: ['20_30', '30_40'],
  },
  {
    id: 'tpl_gold',
    name: 'Purchase of Gold',
    category: 'GOLD_PURCHASE',
    description: 'Accumulate gold as a long-term investment or for family milestones',
    icon: 'Coins',
    defaultTargetYears: 5,
    defaultAmount: 500000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_sabbatical',
    name: 'Sabbatical / Career Break',
    category: 'SABBATICAL',
    description: 'Save enough to take a planned career break without financial stress',
    icon: 'Coffee',
    defaultTargetYears: 3,
    defaultAmount: 600000,
    suggestedAgeGroups: ['20_30', '30_40', '40_50'],
  },
  {
    id: 'tpl_charity',
    name: 'Charity / Philanthropy',
    category: 'CHARITY',
    description: 'Set aside funds for causes, donations, or community giving',
    icon: 'HandHeart',
    defaultTargetYears: 2,
    defaultAmount: 100000,
    suggestedAgeGroups: ['30_40', '40_50', '50_PLUS'],
  },
  {
    id: 'tpl_child_birth',
    name: 'Child Birth & Early Years',
    category: 'CHILD_BIRTH',
    description: 'Plan for maternity, delivery, and early childhood expenses',
    icon: 'Baby',
    defaultTargetYears: 2,
    defaultAmount: 500000,
    suggestedAgeGroups: ['20_30', '30_40'],
  },
  {
    id: 'tpl_medical',
    name: 'Medical Corpus',
    category: 'MEDICAL_CORPUS',
    description: 'Build a dedicated fund for medical emergencies and senior care',
    icon: 'Stethoscope',
    defaultTargetYears: 10,
    defaultAmount: 1000000,
    suggestedAgeGroups: ['40_50', '50_PLUS'],
  },
]
