import type { ProductMaster } from '@/types'

const now = new Date().toISOString()

/**
 * ─── PLACEHOLDER PRODUCT MASTER (F-02) ────────────────────────────────────────
 * Schema is final. The DATA below — especially `isUjjivanProduct`, `returnHistory`
 * (XIRR), `ctaLink`, and `priorityRank` — is placeholder pending the real Ujjivan
 * product list from Pratik (open question / blocker in the spec).
 *
 * Coverage-mapping convention:
 *   isUjjivanProduct = true  → real Ujjivan offering (shown first, no disclosure)
 *   isUjjivanProduct = false → third-party "Other market option" (carries disclosure)
 *
 * For a Small Finance Bank, deposits/insurance/PPF/NPS are treated as Ujjivan
 * offerings; AMC products (MFs, SGB, G-Secs, direct equity) are third-party here.
 * Update once the authoritative list is received.
 */
export const DEFAULT_PRODUCTS: ProductMaster[] = [
  {
    id: 'prod_equity_mf',
    name: 'Equity Mutual Fund',
    category: 'MUTUAL_FUND',
    description: 'Diversified equity funds investing in stock markets for long-term capital appreciation',
    minInvestment: 500,
    expectedReturnPercent: 12,
    riskTier: 'HIGH',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'HOME_PURCHASE', 'BUSINESS',
      'REAL_ESTATE', 'LEGACY_INHERITANCE', 'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'CHILD_BIRTH',
    ],
    isActive: true,
    tags: ['growth', 'long-term', 'equity'],
    isUjjivanProduct: false,
    rmPitch: 'Best long-term wealth creator for goals 7+ years away — stay invested through ups and downs.',
    priorityRank: 1,
    pros: ['Highest long-term growth potential', 'Beats inflation comfortably over 7+ years', 'Start with just ₹500/month'],
    cons: ['Can fall 20–30% in bad years', 'Not suitable for goals under 5 years'],
    alternateProductId: 'prod_balanced_mf',
    returnHistory: { xirr3yr: 15.2, xirr5yr: 13.8, xirr10yr: 12.5, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_sip',
    name: 'SIP — Systematic Investment Plan',
    category: 'SIP',
    description: 'Regular monthly investment in mutual funds through a disciplined approach',
    minInvestment: 500,
    expectedReturnPercent: 11,
    riskTier: 'MEDIUM',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40', '40_50'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'MARRIAGE', 'HOME_PURCHASE', 'BUSINESS',
      'REAL_ESTATE', 'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'LEGACY_INHERITANCE',
      'CHILD_BIRTH', 'GOLD_PURCHASE',
    ],
    isActive: true,
    tags: ['sip', 'disciplined', 'monthly'],
    isUjjivanProduct: false,
    rmPitch: 'The disciplined way to invest — a fixed amount every month, rupee-cost averaged across markets.',
    priorityRank: 1,
    pros: ['Builds a saving habit automatically', 'Averages out market volatility', 'Fully flexible — pause or step up anytime'],
    cons: ['Returns still depend on the underlying fund', 'Needs consistency to work well'],
    alternateProductId: 'prod_equity_mf',
    returnHistory: { xirr3yr: 13.0, xirr5yr: 12.0, xirr10yr: 11.5, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_ppf',
    name: 'PPF — Public Provident Fund',
    category: 'PPF',
    description: 'Government-backed 15-year lock-in scheme with tax-free returns',
    minInvestment: 500,
    expectedReturnPercent: 7.1,
    riskTier: 'LOW',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'MARRIAGE',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'CHILD_BIRTH', 'LEGACY_INHERITANCE',
    ],
    isActive: true,
    tags: ['tax-free', 'government', 'long-term'],
    isUjjivanProduct: true,
    rmPitch: 'Government-guaranteed, fully tax-free returns — the safest cornerstone for a long-term goal.',
    priorityRank: 1,
    pros: ['Completely tax-free (EEE)', 'Sovereign guarantee — zero risk', 'Great for disciplined 15-year saving'],
    cons: ['15-year lock-in with limited early withdrawal', '₹1.5L annual contribution cap'],
    alternateProductId: 'prod_nps',
    ctaLink: 'https://www.ujjivansfb.in/ppf',
    returnHistory: { xirr3yr: 7.1, xirr5yr: 7.1, xirr10yr: 7.6, asOf: '2026-03' },
    termRangeMonths: { min: 180, max: 180 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_nps',
    name: 'NPS — National Pension System',
    category: 'NPS',
    description: 'Government retirement savings scheme with equity and debt mix',
    minInvestment: 500,
    expectedReturnPercent: 10,
    riskTier: 'MEDIUM',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50'],
    suitableGoalCategories: ['RETIREMENT', 'LEGACY_INHERITANCE'],
    isActive: true,
    tags: ['pension', 'retirement', 'tax-saving'],
    isUjjivanProduct: true,
    rmPitch: 'Extra ₹50,000 tax deduction on top of 80C, plus a low-cost market-linked retirement corpus.',
    priorityRank: 2,
    pros: ['Additional ₹50k tax break under 80CCD(1B)', 'Lowest-cost market-linked pension', 'Auto-rebalances equity/debt with age'],
    cons: ['Locked till age 60', 'Part of maturity must buy an annuity'],
    alternateProductId: 'prod_ppf',
    ctaLink: 'https://www.ujjivansfb.in/nps',
    returnHistory: { xirr3yr: 11.5, xirr5yr: 10.8, xirr10yr: 10.2, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_fd',
    name: 'Fixed Deposit',
    category: 'FIXED_DEPOSIT',
    description: 'Bank fixed deposits offering guaranteed returns over a fixed tenure',
    minInvestment: 1000,
    expectedReturnPercent: 6.5,
    riskTier: 'LOW',
    liquidityScore: 3,
    taxEfficiency: 'LOW',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'EMERGENCY_FUND', 'MEDICAL_CORPUS', 'TRAVEL', 'VEHICLE',
      'LOAN_FORECLOSURE', 'SABBATICAL', 'CHARITY', 'GOLD_PURCHASE',
      'CRITICAL_ILLNESS', 'FAMILY_HEALTH',
    ],
    isActive: true,
    tags: ['safe', 'guaranteed', 'fixed-income'],
    isUjjivanProduct: true,
    rmPitch: 'Guaranteed returns with Ujjivan — among the most competitive FD rates for short-term goals.',
    priorityRank: 1,
    pros: ['Capital fully protected', 'Predictable, guaranteed payout', 'Flexible tenures from 7 days to 10 years'],
    cons: ['Interest is fully taxable', 'Returns may trail inflation over long periods'],
    alternateProductId: 'prod_rdp',
    ctaLink: 'https://www.ujjivansfb.in/fixed-deposit',
    returnHistory: { xirr3yr: 6.8, xirr5yr: 6.6, xirr10yr: 6.9, asOf: '2026-03' },
    termRangeMonths: { min: 1, max: 120 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_gold',
    name: 'Gold — Sovereign Gold Bond',
    category: 'GOLD',
    description: 'RBI-issued bonds linked to gold price with additional interest',
    minInvestment: 5000,
    expectedReturnPercent: 8,
    riskTier: 'MEDIUM',
    liquidityScore: 2,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'MARRIAGE', 'EMERGENCY_FUND',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'GOLD_PURCHASE', 'LEGACY_INHERITANCE',
    ],
    isActive: true,
    tags: ['gold', 'hedge', 'inflation-proof'],
    isUjjivanProduct: false,
    rmPitch: 'Own gold the smart way — tracks gold price, pays 2.5% extra interest, and is tax-free at maturity.',
    priorityRank: 1,
    pros: ['Extra 2.5% annual interest over physical gold', 'Tax-free capital gains if held to maturity', 'No storage or purity worries'],
    cons: ['8-year maturity (exit window from year 5)', 'Gold prices can stay flat for years'],
    alternateProductId: 'prod_debt_mf',
    returnHistory: { xirr3yr: 12.0, xirr5yr: 9.5, xirr10yr: 9.0, asOf: '2026-03' },
    termRangeMonths: { min: 96, max: 96 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_term_insurance',
    name: 'Term Life Insurance',
    category: 'INSURANCE',
    description: 'Pure life cover for financial protection of dependents',
    minInvestment: 5000,
    expectedReturnPercent: 0,
    riskTier: 'LOW',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'HOME_PURCHASE', 'LIFE_PROTECTION',
    ],
    isActive: true,
    tags: ['protection', 'life-cover', 'dependents'],
    isUjjivanProduct: true,
    rmPitch: 'The first thing every earner with dependents needs — large cover for a very small premium.',
    priorityRank: 1,
    pros: ['Very high cover at low cost', 'Secures the family if income stops', 'Premiums qualify for 80C'],
    cons: ['No payout if you survive the term (pure protection)', 'Premium rises sharply if bought later in life'],
    alternateProductId: 'prod_ulip',
    ctaLink: 'https://www.ujjivansfb.in/insurance/term-life',
    returnHistory: { xirr3yr: null, xirr5yr: null, xirr10yr: null, asOf: null },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_health_insurance',
    name: 'Health Insurance',
    category: 'INSURANCE',
    description: 'Comprehensive health cover for medical emergencies',
    minInvestment: 3000,
    expectedReturnPercent: 0,
    riskTier: 'LOW',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'MEDICAL_CORPUS', 'EMERGENCY_FUND', 'CRITICAL_ILLNESS', 'FAMILY_HEALTH',
    ],
    isActive: true,
    tags: ['health', 'medical', 'protection'],
    isUjjivanProduct: true,
    rmPitch: 'One hospital bill can wipe out years of savings — health cover protects the whole plan.',
    priorityRank: 2,
    pros: ['Shields savings from medical shocks', 'Cashless treatment at network hospitals', 'Premiums deductible under 80D'],
    cons: ['Pre-existing conditions have a waiting period', 'Premiums rise with age and claims'],
    ctaLink: 'https://www.ujjivansfb.in/insurance/health',
    returnHistory: { xirr3yr: null, xirr5yr: null, xirr10yr: null, asOf: null },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_balanced_mf',
    name: 'Balanced / Hybrid Fund',
    category: 'MUTUAL_FUND',
    description: 'Mix of equity and debt providing moderate risk and returns',
    minInvestment: 500,
    expectedReturnPercent: 9,
    riskTier: 'MEDIUM',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'MARRIAGE', 'MEDICAL_CORPUS',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'REAL_ESTATE', 'LEGACY_INHERITANCE',
      'CHARITY', 'SABBATICAL',
    ],
    isActive: true,
    tags: ['balanced', 'hybrid', 'moderate'],
    isUjjivanProduct: false,
    rmPitch: 'A smoother ride than pure equity — automatically balances growth and stability in one fund.',
    priorityRank: 2,
    pros: ['Lower swings than pure equity', 'Auto-rebalances equity and debt', 'Good middle-ground for 5–7 year goals'],
    cons: ['Lower upside than pure equity', 'Still carries some market risk'],
    alternateProductId: 'prod_debt_mf',
    returnHistory: { xirr3yr: 10.5, xirr5yr: 9.8, xirr10yr: 9.5, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_debt_mf',
    name: 'Debt Mutual Fund',
    category: 'MUTUAL_FUND',
    description: 'Funds investing in bonds and fixed income securities',
    minInvestment: 500,
    expectedReturnPercent: 7,
    riskTier: 'LOW',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'MEDICAL_CORPUS', 'TRAVEL', 'VEHICLE',
      'LOAN_FORECLOSURE', 'SABBATICAL', 'CHARITY',
    ],
    isActive: true,
    tags: ['debt', 'bonds', 'low-risk'],
    isUjjivanProduct: false,
    rmPitch: 'Steadier than equity with better liquidity than an FD — ideal for 1–3 year goals.',
    priorityRank: 3,
    pros: ['More stable than equity', 'Easy to redeem when needed', 'Tax-efficient for longer holding'],
    cons: ['Modest returns', 'Sensitive to interest-rate moves'],
    alternateProductId: 'prod_fd',
    returnHistory: { xirr3yr: 7.2, xirr5yr: 7.0, xirr10yr: 7.5, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_direct_equity',
    name: 'Direct Equity (Stocks)',
    category: 'EQUITY',
    description: 'Direct investment in listed company stocks via stock exchange',
    minInvestment: 1000,
    expectedReturnPercent: 14,
    riskTier: 'HIGH',
    liquidityScore: 5,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40'],
    suitableGoalCategories: [
      'RETIREMENT', 'BUSINESS', 'HOME_PURCHASE', 'REAL_ESTATE', 'LEGACY_INHERITANCE',
    ],
    isActive: true,
    tags: ['stocks', 'high-growth', 'volatile'],
    isUjjivanProduct: false,
    rmPitch: 'Highest growth potential for hands-on investors who can stomach volatility.',
    priorityRank: 2,
    pros: ['Highest upside potential', 'Full control over holdings', 'Most liquid — sell any trading day'],
    cons: ['High volatility and concentration risk', 'Needs research and active monitoring'],
    alternateProductId: 'prod_equity_mf',
    returnHistory: { xirr3yr: 16.0, xirr5yr: 14.5, xirr10yr: 13.0, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_liquid_mf',
    name: 'Liquid Fund',
    category: 'MUTUAL_FUND',
    description: 'Ultra-short term fund for parking emergency money with easy redemption',
    minInvestment: 500,
    expectedReturnPercent: 5.5,
    riskTier: 'LOW',
    liquidityScore: 5,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'EMERGENCY_FUND', 'TRAVEL', 'LOAN_FORECLOSURE', 'SABBATICAL',
      'CRITICAL_ILLNESS', 'CHARITY',
    ],
    isActive: true,
    tags: ['liquid', 'emergency', 'short-term'],
    isUjjivanProduct: false,
    rmPitch: 'Park your emergency fund here — earns more than a savings account with same-day access.',
    priorityRank: 4,
    pros: ['Withdraw within 24 hours', 'Beats savings-account interest', 'Very low risk'],
    cons: ['Returns lower than equity/debt funds', 'Not for long-term wealth building'],
    alternateProductId: 'prod_fd',
    returnHistory: { xirr3yr: 6.0, xirr5yr: 5.8, xirr10yr: 6.2, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_bonds',
    name: 'Government Bonds',
    category: 'BONDS',
    description: 'Central and state government securities with low risk and stable returns',
    minInvestment: 10000,
    expectedReturnPercent: 7.5,
    riskTier: 'LOW',
    liquidityScore: 2,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'MEDICAL_CORPUS', 'LEGACY_INHERITANCE', 'CHARITY',
    ],
    isActive: true,
    tags: ['government', 'bonds', 'safe'],
    isUjjivanProduct: false,
    rmPitch: 'Lock in a fixed government-backed yield for long-term, worry-free income.',
    priorityRank: 1,
    pros: ['Sovereign-backed safety', 'Predictable long-term yield', 'Good for capital preservation'],
    cons: ['Lower liquidity before maturity', 'Price falls if rates rise'],
    alternateProductId: 'prod_debt_mf',
    returnHistory: { xirr3yr: 7.4, xirr5yr: 7.3, xirr10yr: 7.6, asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_ulip',
    name: 'ULIP — Unit Linked Insurance Plan',
    category: 'INSURANCE',
    description: 'Combined insurance and investment product with market-linked returns',
    minInvestment: 2000,
    expectedReturnPercent: 8,
    riskTier: 'MEDIUM',
    liquidityScore: 2,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'CHILD_BIRTH', 'LIFE_PROTECTION', 'CHILDS_MARRIAGE',
    ],
    isActive: true,
    tags: ['insurance', 'investment', 'tax-saving'],
    isUjjivanProduct: true,
    rmPitch: 'Insurance plus market-linked investment in one plan, with tax-free maturity.',
    priorityRank: 3,
    pros: ['Combines cover and investment', 'Tax-free maturity under 10(10D)', 'Switch funds without tax'],
    cons: ['Higher charges in early years', '5-year lock-in', 'Cover is lower than a pure term plan'],
    alternateProductId: 'prod_term_insurance',
    ctaLink: 'https://www.ujjivansfb.in/insurance/ulip',
    returnHistory: { xirr3yr: 8.5, xirr5yr: 8.0, xirr10yr: 7.5, asOf: '2026-03' },
    termRangeMonths: { min: 60, max: 240 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_rdp',
    name: 'Recurring Deposit',
    category: 'FIXED_DEPOSIT',
    description: 'Monthly fixed deposit scheme with guaranteed returns',
    minInvestment: 500,
    expectedReturnPercent: 6,
    riskTier: 'LOW',
    liquidityScore: 3,
    taxEfficiency: 'LOW',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'TRAVEL', 'VEHICLE', 'MARRIAGE', 'EMERGENCY_FUND',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'GOLD_PURCHASE', 'LOAN_FORECLOSURE',
      'SABBATICAL', 'CHARITY', 'CHILD_BIRTH',
    ],
    isActive: true,
    tags: ['safe', 'monthly', 'guaranteed'],
    isUjjivanProduct: true,
    rmPitch: 'Save a fixed amount every month at a guaranteed rate — perfect for a near-term goal.',
    priorityRank: 2,
    pros: ['Builds a monthly saving habit', 'Guaranteed returns', 'Low ₹500 start'],
    cons: ['Interest is taxable', 'Penalty on early closure'],
    alternateProductId: 'prod_fd',
    ctaLink: 'https://www.ujjivansfb.in/recurring-deposit',
    returnHistory: { xirr3yr: 6.0, xirr5yr: 6.0, xirr10yr: 6.2, asOf: '2026-03' },
    termRangeMonths: { min: 6, max: 120 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_flexicap_new',
    name: 'Flexi Cap Fund (New Launch)',
    category: 'MUTUAL_FUND',
    description: 'Recently launched flexi-cap fund investing across large, mid and small caps',
    minInvestment: 500,
    expectedReturnPercent: 13,
    riskTier: 'HIGH',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40'],
    suitableGoalCategories: ['RETIREMENT', 'EDUCATION', 'HOME_PURCHASE', 'BUSINESS'],
    isActive: true,
    tags: ['growth', 'new-fund', 'equity'],
    isUjjivanProduct: false,
    rmPitch: 'A newer fund with a strong early track record — flexible across market caps for long-term growth.',
    priorityRank: 5,
    pros: ['Flexibility to move across market caps', 'Strong since-launch performance'],
    cons: ['Short track record — less than 3 years', 'Higher volatility as a new fund'],
    alternateProductId: 'prod_equity_mf',
    // F-07: too new for 3yr/5yr/10yr — carries a since-inception return instead.
    returnHistory: { xirr3yr: null, xirr5yr: null, xirr10yr: null, xirrSinceInception: 18.5, inceptionDate: '2024-06', asOf: '2026-03' },
    createdAt: now,
    updatedAt: now,
  },
]
