import type { ProductMaster } from '@/types'

const now = new Date().toISOString()

export const DEFAULT_PRODUCTS: ProductMaster[] = [
  {
    id: 'prod_equity_mf',
    name: 'Equity Mutual Fund',
    category: 'MUTUAL_FUND',
    description: 'Diversified equity funds investing in stock markets for long-term capital appreciation',
    minInvestment: 500,
    expectedReturnPercent: 12,
    riskTier: 'HIGH',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'HOME_PURCHASE', 'BUSINESS',
      'REAL_ESTATE', 'LEGACY_INHERITANCE', 'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'CHILD_BIRTH',
    ],
    isActive: true,
    tags: ['growth', 'long-term', 'equity'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_sip',
    name: 'SIP — Systematic Investment Plan',
    category: 'SIP',
    description: 'Regular monthly investment in mutual funds through a disciplined approach',
    minInvestment: 500,
    expectedReturnPercent: 11,
    riskTier: 'MEDIUM',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40', '40_50'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'MARRIAGE', 'HOME_PURCHASE', 'BUSINESS',
      'REAL_ESTATE', 'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'LEGACY_INHERITANCE',
      'CHILD_BIRTH', 'GOLD_PURCHASE',
    ],
    isActive: true,
    tags: ['sip', 'disciplined', 'monthly'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_ppf',
    name: 'PPF — Public Provident Fund',
    category: 'PPF',
    description: 'Government-backed 15-year lock-in scheme with tax-free returns',
    minInvestment: 500,
    expectedReturnPercent: 7.1,
    riskTier: 'LOW',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'MARRIAGE',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'CHILD_BIRTH', 'LEGACY_INHERITANCE',
    ],
    isActive: true,
    tags: ['tax-free', 'government', 'long-term'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_nps',
    name: 'NPS — National Pension System',
    category: 'NPS',
    description: 'Government retirement savings scheme with equity and debt mix',
    minInvestment: 500,
    expectedReturnPercent: 10,
    riskTier: 'MEDIUM',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50'],
    suitableGoalCategories: ['RETIREMENT', 'LEGACY_INHERITANCE'],
    isActive: true,
    tags: ['pension', 'retirement', 'tax-saving'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_fd',
    name: 'Fixed Deposit',
    category: 'FIXED_DEPOSIT',
    description: 'Bank fixed deposits offering guaranteed returns over a fixed tenure',
    minInvestment: 1000,
    expectedReturnPercent: 6.5,
    riskTier: 'LOW',
    liquidityScore: 3,
    taxEfficiency: 'LOW',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'EMERGENCY_FUND', 'MEDICAL_CORPUS', 'TRAVEL', 'VEHICLE',
      'LOAN_FORECLOSURE', 'SABBATICAL', 'CHARITY', 'GOLD_PURCHASE',
      'CRITICAL_ILLNESS', 'FAMILY_HEALTH',
    ],
    isActive: true,
    tags: ['safe', 'guaranteed', 'fixed-income'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_gold',
    name: 'Gold — Sovereign Gold Bond',
    category: 'GOLD',
    description: 'RBI-issued bonds linked to gold price with additional interest',
    minInvestment: 5000,
    expectedReturnPercent: 8,
    riskTier: 'MEDIUM',
    liquidityScore: 2,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'MARRIAGE', 'EMERGENCY_FUND',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'GOLD_PURCHASE', 'LEGACY_INHERITANCE',
    ],
    isActive: true,
    tags: ['gold', 'hedge', 'inflation-proof'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_term_insurance',
    name: 'Term Life Insurance',
    category: 'INSURANCE',
    description: 'Pure life cover for financial protection of dependents',
    minInvestment: 5000,
    expectedReturnPercent: 0,
    riskTier: 'LOW',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'HOME_PURCHASE', 'LIFE_PROTECTION',
    ],
    isActive: true,
    tags: ['protection', 'life-cover', 'dependents'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_health_insurance',
    name: 'Health Insurance',
    category: 'INSURANCE',
    description: 'Comprehensive health cover for medical emergencies',
    minInvestment: 3000,
    expectedReturnPercent: 0,
    riskTier: 'LOW',
    liquidityScore: 1,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'MEDICAL_CORPUS', 'EMERGENCY_FUND', 'CRITICAL_ILLNESS', 'FAMILY_HEALTH',
    ],
    isActive: true,
    tags: ['health', 'medical', 'protection'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_balanced_mf',
    name: 'Balanced / Hybrid Fund',
    category: 'MUTUAL_FUND',
    description: 'Mix of equity and debt providing moderate risk and returns',
    minInvestment: 500,
    expectedReturnPercent: 9,
    riskTier: 'MEDIUM',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'MARRIAGE', 'MEDICAL_CORPUS',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'REAL_ESTATE', 'LEGACY_INHERITANCE',
      'CHARITY', 'SABBATICAL',
    ],
    isActive: true,
    tags: ['balanced', 'hybrid', 'moderate'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_debt_mf',
    name: 'Debt Mutual Fund',
    category: 'MUTUAL_FUND',
    description: 'Funds investing in bonds and fixed income securities',
    minInvestment: 500,
    expectedReturnPercent: 7,
    riskTier: 'LOW',
    liquidityScore: 4,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'MEDICAL_CORPUS', 'TRAVEL', 'VEHICLE',
      'LOAN_FORECLOSURE', 'SABBATICAL', 'CHARITY',
    ],
    isActive: true,
    tags: ['debt', 'bonds', 'low-risk'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_direct_equity',
    name: 'Direct Equity (Stocks)',
    category: 'EQUITY',
    description: 'Direct investment in listed company stocks via stock exchange',
    minInvestment: 1000,
    expectedReturnPercent: 14,
    riskTier: 'HIGH',
    liquidityScore: 5,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40'],
    suitableGoalCategories: [
      'RETIREMENT', 'BUSINESS', 'HOME_PURCHASE', 'REAL_ESTATE', 'LEGACY_INHERITANCE',
    ],
    isActive: true,
    tags: ['stocks', 'high-growth', 'volatile'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_liquid_mf',
    name: 'Liquid Fund',
    category: 'MUTUAL_FUND',
    description: 'Ultra-short term fund for parking emergency money with easy redemption',
    minInvestment: 500,
    expectedReturnPercent: 5.5,
    riskTier: 'LOW',
    liquidityScore: 5,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'EMERGENCY_FUND', 'TRAVEL', 'LOAN_FORECLOSURE', 'SABBATICAL',
      'CRITICAL_ILLNESS', 'CHARITY',
    ],
    isActive: true,
    tags: ['liquid', 'emergency', 'short-term'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_bonds',
    name: 'Government Bonds',
    category: 'BONDS',
    description: 'Central and state government securities with low risk and stable returns',
    minInvestment: 10000,
    expectedReturnPercent: 7.5,
    riskTier: 'LOW',
    liquidityScore: 2,
    taxEfficiency: 'MEDIUM',
    suitableAgeGroups: ['30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'RETIREMENT', 'MEDICAL_CORPUS', 'LEGACY_INHERITANCE', 'CHARITY',
    ],
    isActive: true,
    tags: ['government', 'bonds', 'safe'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_ulip',
    name: 'ULIP — Unit Linked Insurance Plan',
    category: 'INSURANCE',
    description: 'Combined insurance and investment product with market-linked returns',
    minInvestment: 2000,
    expectedReturnPercent: 8,
    riskTier: 'MEDIUM',
    liquidityScore: 2,
    taxEfficiency: 'HIGH',
    suitableAgeGroups: ['20_30', '30_40'],
    suitableGoalCategories: [
      'RETIREMENT', 'EDUCATION', 'CHILD_BIRTH', 'LIFE_PROTECTION', 'CHILDS_MARRIAGE',
    ],
    isActive: true,
    tags: ['insurance', 'investment', 'tax-saving'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod_rdp',
    name: 'Recurring Deposit',
    category: 'FIXED_DEPOSIT',
    description: 'Monthly fixed deposit scheme with guaranteed returns',
    minInvestment: 500,
    expectedReturnPercent: 6,
    riskTier: 'LOW',
    liquidityScore: 3,
    taxEfficiency: 'LOW',
    suitableAgeGroups: ['20_30', '30_40', '40_50', '50_PLUS'],
    suitableGoalCategories: [
      'TRAVEL', 'VEHICLE', 'MARRIAGE', 'EMERGENCY_FUND',
      'CHILDS_MARRIAGE', 'OWN_MARRIAGE', 'GOLD_PURCHASE', 'LOAN_FORECLOSURE',
      'SABBATICAL', 'CHARITY', 'CHILD_BIRTH',
    ],
    isActive: true,
    tags: ['safe', 'monthly', 'guaranteed'],
    createdAt: now,
    updatedAt: now,
  },
]
